### ISSUE TITLE
Scale application display size

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#105]
As a user, I want the application to be scalable to different screen sizes, right now it is hardcoded for ratios around 1080p.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 1 |
| Priority     | High |
| Risk         | High |

# Tasks
- Modify the height distribution of the graph to be based on the view. Right now it's hardcoded. 

# Demo steps
- Should display the graph and the list of messages fine on 4k screens and 1080p.

**Comment by riyaGit** [comment]
Resolved in PR #115

**Comment by riyaGit** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to main page while on a 1080p screen and Select a datetime to generate an orderbook  | N/A    | The orderbook  and the message list should appear proportional to the screen |PASS   |
| Go to main page while on a 4k screen and Select a datetime to generate an orderbook  | N/A    | The orderbook  and the message list should appear proportional to the screen |PASS   |
