### ISSUE TITLE
Set up continuous deployment pipeline

### ISSUE THREAD

**Issue by chimano** [Lercerss/graphelier#109]
For User Story #62 

Have the production environment always have the latest docker image to run the software.

- Publish the docker image as part of the CI
- Pull the newly published image using the production instance and deploy

**Comment by Lercerss** [comment]
Currently, the workflow `push_and_deploy` has 4 jobs which are run in parallel. The `aws-ecs/deploy-service-update` should not be run in parallel with the other 3 jobs, but rather after all of them are done.

**Comment by chimano** [comment]
Implemented in #147
