### ISSUE TITLE
Service best ask and bid over time 

### ISSUE THREAD

**Issue by pvacca97** [Lercerss/graphelier#111]
The frontend will need multiple points over time, for an entire day, determining the best bid or ask to display on a graph.

Related story: [#86] 

# Tasks
- create a new route
- query db to get data at some given time
- return best bid & ask for that time

**Comment by Lercerss** [comment]
Discussion about the back-end data approach to this problem:
- We want to increase the number of orderbook snapshots in our database, which will require #94 to be completed
- When a large time interval is requested, we can use the snapshots as an approximation of the best bid/ask function
- When a smaller time interval is requested, we can apply messages to the snapshots to evaluate the best bid/ask function, knowing the number of message should be small enough to allow for efficient processing
- A small interval should be determined by counting the number of snapshots we have available for the requested time range

**Comment by Lercerss** [comment]
The large interval case can be handled by offloading most of the work to mongo, using an aggregate query with `$lookup` and `$pipeline`. Our existing time indexes should allow this query to be efficient

**Comment by Lercerss** [comment]
We should return a single list of objects containing at least time, best_ask and best_bid.

**Comment by chimano** [comment]
Arch diagram
![TopBookArch](https://user-images.githubusercontent.com/26588048/73142813-2087d680-4061-11ea-8d72-51e54580c526.png)
