### ISSUE TITLE
Add loading icon while loading new order book state

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#123]
As a user, I want to know the application is busy processing my request and not stuck.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 1 |
| Priority     | Medium |
| Risk         | Low |

# Tasks
- Add loading icon when the user selects a new time

# Demo steps
- Select a different time
- While data is being processed, a loading icon is displayed
- Loading icon disappears once processing is done

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by alvyn279** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the orderbook page | N/A | Observe that a graphelier icon pops up with loading | PASS   |
| Select an instrument, and select January 1, 2020 as a day |  N/A    | The orderbook should be displayed along with a graph depicting the best bid and best ask through the selected date | PASS |
| Choose a time | Click on input method | Observe a new orderbook being displayed | PASS |
| Choose a different time | Click on input method | Observe the already mounted top of the book and message list to be greyed out during the load | PASS |
