### ISSUE TITLE
Clicking on messages

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#127]
As a user, I want to be able to click on a message in the message list to move to that message's order book's state.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 2 |
| Priority     | High |
| Risk         | Low |

# Tasks
- Add a click listener on message list rows
- Request `/delta` for the appropriate number of messages, starting from `last_sod_messages`

# Demo steps
- Clicking on message loads that message's order book state

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by riyaGit** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to main page | N/A    | N/A | N/A   |
| Select a datetime to generate an orderbook and message list | Select a message row from the message list | The orderbook state should change reflected the message row selected |PASS   |

**Comment by riyaGit** [comment]
Addressed in pull request #130
