### ISSUE TITLE
Go to most recent message in message list

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#132]
As a user, I want to be able to quickly go to the most recently applied message in the message list instead of scrolling manually until seeing the highlighted message.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 3 |
| Priority     | High |
| Risk         | Low |

# Tasks
- Add button which scrolls to most recent message

# Demo steps
- Scroll the message list for a long time
- Return to most recently applied messages

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the orderbook page | N/A | N/A | N/A   |
| Select an instrument and select any time within January 1, 2020 |  N/A    | The orderbook should be displayed | Not yet tested  |
| Scroll through the message lists| N/A  | N/A | N/A|
| Using a button or a key go back to the most recent message applied on the orderbook| Press "`" on the keyboard  | The most recent message applied must be centered in the components | Not yet tested|
