### ISSUE TITLE
Serve order information based on order id

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#141]
Preprocess order data, investigate storage/processing solutions and serve as a new route based on a given order id and _as-of_ timestamp.

# Tasks
- [x] Investigate algorithm and storage solutions for order information
- [x] Add new route which reads and serves order information based on order id and _as-of_ time

Story #110

**Comment by chimano** [comment]
OrderInfo Architecture
![OrderInfo_Arch](https://user-images.githubusercontent.com/26588048/73128058-c40cb480-3f97-11ea-8484-aea44c0f5aa2.png)

**Comment by chimano** [comment]
Handler tests: [link](https://github.com/Lercerss/graphelier/blob/master/core/graphelier-service/api/hndlrs/orderhandler_test.go)
Model tests: [link](https://github.com/Lercerss/graphelier/blob/master/core/graphelier-service/models/orderinfo_test.go)
