### ISSUE TITLE
Support strict browser CORS policy

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#148]
Some browser policies block outgoing requests from the frontend to the backend due to the different ports.
Error raised in console seems to point to adding the `Access-Control-Allow-Origin` header. I believe this needs to be added to the nginx config.

**Comment by chimano** [comment]
Found this https://enable-cors.org/server_nginx.html

**Comment by Lercerss** [comment]
After further investigation, it appears the backend was blocked by Squarepoint's firewall. Therefore we will be switching to a static IP for our EC2 instance and they will whitelist the port. Our existing CORS setup is correct on the backend side and the frontend server (nginx) should not be concerned with this.

**Comment by Lercerss** [comment]
The firewall issue has been resolved on Squarepoint's side and the app is confirmed to work with the current CORS policies in place.
