### ISSUE TITLE
Timeline of news articles

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#163]
As a user, I want to be able to view news articles relating to various instruments and navigate to the affected instruments to determine the impat.

These articles will be categorized to determine the type of the news' pressure on the book. We will make use of text summarization using natural language processing to display the most important parts of the articles in the timeline. Articles relating to the same subject matter, determined using clustering of the documents, are grouped together on the timeline. The instruments affected by the news will be automatically extracted from the articles then users can select an article and jump to the associated order book state to inspect the effects of its publication.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 13 |
| Priority     | High |
| Risk         | High |

# Tasks
- Present news articles on a timeline
- Summarize the articles content
- Group articles by subject matter
- Determine direction of article's book pressure by categorization
- Extract affected instruments from articles
- Jump from articles to order book snapshot of the right instrument at the right time

# Demo steps
- View the timeline
- Read an article's summary
- Related articles are grouped together
- Click on an article and view the affected instrument's order book state at the time of the article

## Customer signoff
- [ ] Pierre-Marc Fournier

**Comment by panoreak** [comment]
Question - Is it possible that an article would have more than one associated instrument?

**Comment by alvyn279** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the news page | N/A | N/A | Passed  |
| Select a date in the date picker field |  N/A    | The timeline should be displayed with news of that date | Passed |
| Scroll and hit the bottom | N/A   |  The timeline should show newer articles | Passed |
| Scroll and hit the top | N/A   |  The timeline should show older articles | Passed |
| Click on a colored instrument of an article within market hours  | N/A   |  There should be redirection to the orderbook for that timestamp and instrument  | Passed |
