### ISSUE TITLE
Add messages to small interval

### ISSUE THREAD

**Issue by pvacca97** [Lercerss/graphelier#164]
The backend will need to service the case where it is required to send more points than snapshot intervals to the frontend. This requires adding enough messages, spaced out evenly, within the range requested.

Related story: #165 

# Tasks
- Add the small interval case to the existing route `/topbook/{instrument}/{start_timestamp}/{end_timestamp}/{num_points}`
- Get the latest orderbook from the lowwer bound of the interval
- Apply messages evenly until the higher bound of the interval
- Find top of book at each of these points and return the result

**Comment by panoreak** [comment]
I was thinking about the cases where we're requesting very precise data points, and I realized that if the number of nanoseconds between the requested start time and end time is smaller than the number of requested data points, you should limit the number of data points to the number of nanoseconds between that interval.

To put it a different way, you should make sure that there is max one data point per nanosecond timestamp that you return, even if that means that you are returning less data points than the number of data points requested.
