### ISSUE TITLE
Zoom top-of-book graph

### ISSUE THREAD

**Issue by pvacca97** [Lercerss/graphelier#165]
As a user, I want to be able to zoom in to the nanosecond granularity, so I can analyze how the orderbook's best bid and best ask change.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 8      |
| Priority     | High |
| Risk         | High |

# Tasks
- #157 Customize the React Stockcharts library for nanosecond precision compatbility 
- #164 Include backend small interval case

# Demo steps
- Horizontally zooming into the graph to the nanosecond precision

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by alvyn279** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the orderbook page | N/A | N/A | N/A   |
| Select and instrument and type 01/01/2020 in the date picker field |  N/A    | The orderbook should be displayed along with a graph depicting the best bid and best ask through the selected date | Passed |
| Zoom to nanoseconds precision on the graph | Zoom scrolling with mouse wheel or trackpad   |  The graph should visually have loaded more data points | Passed |
| Zoom out | Zoom scrolling with mouse wheel or trackpad   |  The graph should have less data points and a more generic view of best bids and asks | Passed |
