### ISSUE TITLE
Scale on top of book graph is off by an hour

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#170]
The scale for the top of book graph shows that there is data from 8:30AM to 3:00PM. This is not business hours.

This problem might be linked with daylight saving time at the instantiation of `Date` objects.

| Metric       | Value           |
|--------------|-----------------|
| Priority     | High |
| Risk         | Low |

# Tasks
- Instantiate the `Date` objects used by the graph with the correct timezone offset (EDT)

**Comment by Lercerss** [comment]
It appears this was actually not fixed as it re-occurs now, after daylight savings changed again.

**Comment by alvyn279** [comment]
fixed in #202
