### ISSUE TITLE
Automatic playback of messages on the order book

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#175]
As a user, I want to view changes to the order book through time in an animated fashion for educational purposes as well as to better visualize the behavior of an order book.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 13 |
| Priority     | High |
| Risk         | High |

Tasks: #176, #177, #178 
# Tasks
- Prototype animations for all types of order book modifications
- Design a new page for the app
- Implement new component to display animations on the book
- Serve modifications to the order book, possibly as a streamed response or using websockets

# Demo steps
- Open the playback page
- Start playback from a given point in time
- The following modifications to the book are animated as time advances:
  - An order is deleted from the book
  - An order is added to the book
  - An order's quantity is modified (execute or modify)
  - (Tentative) An order moves across price levels

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by Lercerss** [comment]
In terms of design, I propose we adopt a batch approach where modifications to the order book are grouped by small time intervals, say 250ms, and sent to the client at the same regular interval. Modifications are then animated concurrently and finish before the next batch is received. 

Only modifications to the top ~50 price levels (based on display size) are shown to avoid the need to scroll the display.

The service asynchronously prepares the list of modifications sorted by time and sends it to the app at regular intervals. This can be achieved using websockets, possibly allowing the server to keep order book state in memory for the duration of the request.

**Comment by alvyn279** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the orderbook page | N/A | N/A | Passed  |
| Select an instrument and select a date in the date picker field |  N/A    | The graph should show data points for that day and instrument  | Passed |
| Click a time on the graph | N/A  | Orderbook should be loaded for that time | Passed |
| Set the playback settings to 1 message per second | N/A   |  N/A | Passed |
| Click play  | N/A   |  There should be movement on the graph for a single message operation at every second.| Passed |
| Click pause  | N/A   |  The playback should stop | Passed |
| Set the playback settings to 100 milliseconds per second | N/A   |  N/A | Passed |
| Click play  | N/A   |  There should be movement on the graph for multiple message operations at every second.| Passed |
