### ISSUE TITLE
Animate modifications to the order book

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#176]
From the app perspective, we need to implement animations for modifications to the order book.

# Tasks
- Create mockup/prototype of animations for each of the possible modification types:
  - Delete an order
  - Add a new order
  - Modify an order (execute could be a different animation or the same as modify)
  - (Tentative) Move an order across price-levels
- Create component to apply animations on an order book state given a list of modifications

Story #175.

**Comment by chimano** [comment]
New Order:
![NEW_ORDER](https://user-images.githubusercontent.com/26588048/74108124-ff38e700-4b44-11ea-8ef1-57bbd9969be3.gif)

Delete Order:
![DELETE_ORDER](https://user-images.githubusercontent.com/26588048/74108130-0bbd3f80-4b45-11ea-86a0-07fd99460220.gif)

**Comment by chimano** [comment]
Modifying/Executing order:
![MODIFY_ORDER](https://user-images.githubusercontent.com/26588048/74110465-dae80500-4b5a-11ea-81d1-ff1d1036ff1b.gif)

**Comment by chimano** [comment]
New Price Level:
![Add_Price](https://user-images.githubusercontent.com/26588048/75292096-877be500-57f1-11ea-8612-0bfb9f77890d.gif)
Delete Price Level:
![Remove_Price](https://user-images.githubusercontent.com/26588048/75292111-8f3b8980-57f1-11ea-9fe4-502e483f4ac9.gif)
