### ISSUE TITLE
New playback page layout

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#177]
From the app perspective, we need to add a new page to accommodate the playback feature. It should have at least an order book snapshot view, as well as some basic controls to start/stop the playback and possibly adjust speed.

Based on stakeholder feedback, we could also add the list of messages or the graph to this page if the information they provide is relevant.

# Tasks
- Mockup page layout alternatives
- Add new route to the toolbar
- Compose existing and new components to form playback page layout

Story #175.

**Comment by Lercerss** [comment]
We could have 3 components: an order book snapshot view representing L3, an overview of the book's shape representing L2 and a small zoomed-in graph of the best bid and ask representing L1.

**Comment by chris-baur** [comment]
![playback01](https://user-images.githubusercontent.com/15928554/74113151-7b94ef80-4b70-11ea-820f-c17e8a65e5cd.png)
![playback02](https://user-images.githubusercontent.com/15928554/74113152-7c2d8600-4b70-11ea-9fde-3b1366c55b22.png)
![playback03](https://user-images.githubusercontent.com/15928554/74113153-7c2d8600-4b70-11ea-9a11-4f66386ec4da.png)
![playback04](https://user-images.githubusercontent.com/15928554/74113154-7cc61c80-4b70-11ea-98e6-7f70fc00330e.png)
![playback05](https://user-images.githubusercontent.com/15928554/74113155-7cc61c80-4b70-11ea-91cd-bdeda24f07a1.png)
![playback06](https://user-images.githubusercontent.com/15928554/74113156-7d5eb300-4b70-11ea-8b81-a736f7ba3721.png)

**Comment by chris-baur** [comment]
![playback07](https://user-images.githubusercontent.com/15928554/74113286-4046f080-4b71-11ea-9ada-a797639f0150.png)

**Comment by chris-baur** [comment]
![playback08](https://user-images.githubusercontent.com/15928554/74113448-2659dd80-4b72-11ea-9f5a-82dc52c916e4.png)

**Comment by Lercerss** [comment]
Because of the frequency of messages, I think it would be best to omit the list of messages in this layout.
Also I think we should investigate reducing the size of the graph to have more space for the order book (L3 view)

**Comment by Lercerss** [comment]
From @chris-baur 
![image](https://user-images.githubusercontent.com/34099471/74469355-7c789a80-4e6a-11ea-83c6-89cdb22f9d06.png)
