### ISSUE TITLE
Unable to zoom out back to a full day's view

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#191]
After zooming in a lot (interval become less than 5 minutes long), the graph is unable to zoom out fully again. Instead, it prevents zooming out further than an interval around 25 minutes. Clicking on the graph, panning or zooming in and out again do not seem to resolve the issue. Inspecting the console logs, it seems the graph still sends a new request on scroll but the bounds don't change.

**Comment by Lercerss** [comment]
On a separate note, it seems sometimes the graph does not load more points when panning. Exact steps to reproduce it are unclear, but once it starts occurring the only way to load more points is to zoom the graph.

**Comment by alvyn279** [comment]
Two things to note:

- Zooming with a mouse wheel on Chrome works fine it seems, only using touchpad zoom in/out leads to the whole page being dragged
- There indeed seems to be an issue with panning not loading more points, although the steps to reproduce seem to be inconsistent.
