### ISSUE TITLE
Layout of the order details pane breaks

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#196]
Clicking on an order for the first time results in a broken layout for the order details pane.

**Comment by panoreak** [comment]
Here are some examples:
1)
![image](https://user-images.githubusercontent.com/25068506/76017327-6c455f80-5eec-11ea-8eb3-563126b53b0a.png)

2)
![image](https://user-images.githubusercontent.com/25068506/76017365-77988b00-5eec-11ea-9acc-8ab2ddc7661e.png)

3)
![image](https://user-images.githubusercontent.com/25068506/76017450-9dbe2b00-5eec-11ea-9c7b-22f18fd631c0.png)

**Comment by Lercerss** [comment]
I consistently get the 3rd case when opening the Order Info pane for the first time on prod.

**Comment by alvyn279** [comment]
This seems to be un-reproducible in a development environment. Happens consistently at first load on [production](http://18.218.121.174/orderbook).
