### ISSUE TITLE
Serve processed news data

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#201]
We need a new service to provide processed news data for the timeline. It should be separate from our existing Go backend to avoid tangling concerns. To reduce development time, we could build it in Python using Flask.

Related story: #163 

## Tasks
- Initialize Flask server code base in news directory
- Connect news service to the news mongo db
- Add endpoints to read, process and serve data for the frontend timeline

**Comment by alvyn279** [comment]
Implemented in #220 and #222

**Comment by alvyn279** [comment]
Tests for new news clusters route:
https://github.com/Lercerss/graphelier/blob/master/news/service/views.spec.py
