### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#23]
As a developer, I want to have a continuous integration workflow established to automatically build and test the artifacts affected by my changes.

Tasks: #26, #36

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 3 |
| Priority     | High |
| Risk         | Low |

# Tasks
- Decide on CI host
- Add build and test steps for frontend
- Add build and test steps for backend
- Add build and test steps for scripts

# Demo steps
- Go to CI host
- Open latest build
- See test reports and build artifacts for the project

## Customer signoff
- [x] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to CI host | N/A    | N/A | N/A   |
| Go to the latest build triggered by a PR | N/A    | The results from building, linting and testing all the components of the project |PASS   |
