### ISSUE TITLE
Distinguish orders by their relative size

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#27]
As user, I want orders to be displayed with different sizes based on their quantity, so I can quickly distinguish orders and grasp the total volume for a given price level.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 2 |
| Priority     | Medium |
| Risk         | Low |

# Tasks
- Determine proper scaling for all orders to fit into the page (log, percentage of max volume)
- Scale each order based on its share quantity inside its price level

# Demo steps
- Open the order book fixed time display
- Notice that each order has a varying size based on its share quantity

## Customer signoff
- [ ] Pierre-Marc Fournier
- [ ] TA

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to main page | N/A    | N/A | N/A   |
| Select a datetime to generate an orderbook | N/A    | The orderbook should appear with the size of the orders being proportional to their share quantities |PASS   |
