### ISSUE TITLE
Add time dimension to order book display

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#28]
As a user, I want to select the time for which the order book is displayed. Furthermore, I want to be able to step randomly across time or step through time one message at a time.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5 |
| Priority     | High |
| Risk         | High |

# Tasks
- Allow moving through time in the front-end
- Serve deltas when requesting message steps from service
- Refresh display with new data

# Demo steps
- Open the order book display
- Select a different time in the future
- Select a different time in the past
- Notice that the order book display is refreshed with data for the selected time
- Move one message forward in time
- Move one message backward in time
- Notice that the order book is refreshed with data affected by the message

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by alvyn279** [comment]
Finished implementation in #70

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to main page | N/A    | N/A | N/A   |
| Select a datetime to generate an orderbook | N/A    | A table should appear, representing the order book at the selected point in time.  | -   |
| Select another datetime to generate an orderbook | N/A    | A different table should appear.  | -   |
| Go forward in time by 1 message | N/A    | A row on the table should be modified.  | -   |
| Go backward in time by 1 message | N/A    | The modified row should get reverted.  | -   |
