### ISSUE TITLE
Extend dataset to cover substantial time range for multiple instruments

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#34]
As a user, I want to visualize data from more than one instrument and many days.

According to our current approximation, for 253 trading days (a full year) with snapshots every 10 seconds, the dataset size for SPY is around 40 GB.
We can enrich this by adding other instruments with smaller time ranges easily, for approximately less than 5 GB.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 3 |
| Priority     | High |
| Risk         | High |

# Tasks
- Extend current SPY data to a full day
- Replicate full day's data over 253 trading days
- Use data samples from AMZN, AAPL, MSFT, INTC and GOOG to create 2-3 weeks of data for these instruments.

# Demo steps
- Display list of instruments available
- Display data for SPY more than 6 months apart

## Customer signoff
- [ ] Pierre-Marc Fournier
- [ ] TA

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Import the data using the extender | N/A    | N/A | N/A   |
| Open the database | N/A    | N/A |N/A   |
| Go to the messages collection | N/A    | There should be a day's worth of messages in it |PASS   |
| Go to the orderbooks collection | N/A    | There should be a day's worth of orderbooks in it |PASS  |
