### ISSUE TITLE
Order book fixed time display

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#5]
As a user, I want to see the state of the order book for a given point in time, so I can see how many orders make up a given price level.

To represent the order book state, orders should be grouped by price and have a different size based on each order's share quantity.

Tasks: #7, #9, #10, #11, #12

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5      |
| Priority     | High |
| Risk         | High |

# Tasks
- Load data from [LOBSTER sample](https://lobsterdata.com/info/DataSamples.php) into prepared format
- Serve prepared data from the service
- Display data from service in the app

# Demo steps
- Open app and navigate to the order book fixed time display
- Notice that orders are grouped by price level
- Notice that orders can be distinguished by their share quantity

## Customer signoff
- [x] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expeted Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Open the web application | N/A    | A table representing the orderbook at an arbitrary point in time where orders are grouped by price | PASS   |
