### ISSUE TITLE
List of messages over time

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#50]
As a user, I want to see messages that affect the current orderbook in a list ordered by time, with the most recent message highlighted. These messages will help in understanding the lifecycle of the orderbook and how each message modifies the state.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5 |
| Priority     | High |
| Risk         | Medium |

# Tasks
- Mockup
- Add a component to display the list of messages with highlighting for the most recent message
- Serve list of messages from the service, with pagination
- Request pages of messages from the service as the user scrolls through the list of messages

# Demo steps
- Navigate to the orderbook display
- Notice that the list of messages is displayed along with the orderbook state
- The current message (orderbook state) is highlighted 
- Scrolling through messages shows more messages in either the future or the past

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
Here's the API contract 
```
URL: /messages/{instrument}/{sod_offset}

Additional query parameters:
nMessage: int
nMessages indicates the number of messages that will be included in the page
if nMessages > 0, serves all messages m where sod_offset < m <= sod_offset + nMessages
if nMessages < 0, serves all messages m where sod_offset + nMessages <= m < sod_offset

By default nMessages = 20
Example request: /messages/SPY/1572408000000000019?nMessages=50

Response object:
{
  "pageInfo": {
    "nMessages": int,
    "sod_offset": int
  },
  "messages": [
     {"instrument": string,
      "timestamp": int,
      "message_type": int,
      "order_id": int,
      "share_qty": int,
      "price": float,
      "direction": int,
      "sod_offset": int
    },...]
  ]
}
NOTE: messages will always be sorted in ascending order using sod_offset
```

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to main page | N/A    | N/A | N/A   |
| Select a datetime to generate an orderbook | N/A    | The list of messages relevant to the selected timestamp should appear  | -   |
