### ISSUE TITLE
Cache dependencies in CI build, keep going when tests/lint steps fail

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#55]
As a developer, I want to have quicker build and see all test/lint results even on a failed build. Quicker builds allow for faster response to errors while seeing all testing or linting results at once help address all issues found at once.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 2 |
| Priority     | Medium |
| Risk         | Low |

# Tasks
- Cache container dependencies to make commands such as `go get` and `npm install` execute faster.
- Separate test & lint build steps by component (app, service, scripts) into jobs and let other jobs run even if one component's job has failed.

# Demo steps
- Builds complete in <4 mins
- Test failures on the app do not abort the build early

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Go to CI host | N/A    | N/A | N/A   |
| Go to the latest build triggered by a PR | N/A    | The duration of the build should be less than 4 minutes. The build should be split into multiple jobs |PASS   |
