### ISSUE TITLE
Web hosting

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#62]
As a user, I want to be able to use Graphelier without needing to build and run it on my local environment.

As a developer, I want to be able to receive usage logs and feedback from users through a central hosted solution.

Tasks: #107, #109

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5 |
| Priority     | Medium |
| Risk         | Medium |

# Tasks
- Add a production configuration for the app
- Select an appropriate hosting service based on our needs and costs
- Manually initialize the server to run the app, service and database
- Populate database
- Setup continuous deployment pipeline as part of the CI

# Demo steps
- Graphelier can be accessed through a public url
- Pull requests merged into master are automatically picked up by the server

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
Possible hosting solutions:
OPTION 1:
- Hosting everything on an AWS EC2 instance (c5d.large, 2vCPU, 4GB RAM, 50GB SSD)
    - Price: ~$70
Total price: $70
OPTION 2:
- Host backend on GCP's App Engine
    - Price: Free
- Host frontend on Heroku
    - Price: Free
- Migrate database to AWS DynamoDB
    - Price: ~$20 - $30
    - Backend will need to be refactored. Requires extra effort.

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the url pointing to the server the application is hosted on | Visit: http://ec2-18-188-177-125.us-east-2.compute.amazonaws.com/    | The application's home page should appear | PASS   |
| Select an instrument and select any time within January 1, 2020 |  N/A    | The orderbook should be displayed | PASS   |

**Comment by chimano** [comment]
Production environment
![AWS_Infra](https://user-images.githubusercontent.com/26588048/73125745-4dac8a00-3f78-11ea-8f9c-fd337c9e9cb2.png)
