### ISSUE TITLE
Time interval displayed is in UTC

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#65]
App displays a time range from 9:30 AM to 4:00 PM which should be in EST, but it appears to be in UTC. The time range should correspond to the market open hours which are in EST for NASDAQ.

From browser logs, time `2012-06-21 14:28:47.394714904` is converted to `1340288927394715000` which according to [epochconverter](epochconverter.com) corresponds to `2012-06-21 14:28:47.394714904+0` while it should be converted to `2012-06-21 14:28:47.394714904-4`.

**Comment by alvyn279** [comment]
Solved in #80
