### ISSUE TITLE
Milestone Document - Release 1

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#71]
As a developer, I need to fill the milestone document with all relevant information related to Release 1.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5 |
| Priority     | High |
| Risk         | High |

# Tasks
- Fill each section of the milestone document

**Comment by panoreak** [comment]
Linked everyone's github account, linked Iterations and counted each Iteration's number of stories and points

**Comment by Lercerss** [comment]
- Add acceptance tests for all stories

**Comment by pvacca97** [comment]
- Added naming conventions for javascript, python, and go
- Added key backend files stating their purpose
- Added key backend testing files stating their purpose
