### ISSUE TITLE
Fix all front-end developer warnings

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#75]
When compiling the front-end application, there are multiple warnings and errors related to React component properties or eslint comments at compile-time (that don't affect functionality). These should be fixed to improve the readability of the JS console output.

# Tasks
- Go through all these warnings and fix them

**Comment by Lercerss** [comment]
Note that compile-time warnings will fail the build step for the app.

**Comment by alvyn279** [comment]
Create-React-App `react-scripts` needs some extra overriding to specify custom styling/linting in `.eslintrc.json`. This is done through passing an ENV var to the react scripts command that will unlock [experimental extending of linting config](https://create-react-app.dev/docs/setting-up-your-editor/#experimental-extending-the-eslint-config).

Starting the server with `npm start` should now have the following command:
```sh
EXTEND_ESLINT=true react-scripts start
```

**Comment by alvyn279** [comment]
Soved in #84
