### ISSUE TITLE
Allow selection of the displayed instrument

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#77]
As a user I want to be able to select the instrument for which data is being displayed to allow visualization of data for more than just _SPY_.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 3 |
| Priority     | Medium |
| Risk         | Low |

# Tasks
- Add a dropdown select to choose from available instruments
- Pass selected instrument in requests to the service
- Keep track of available instruments in the service/database

# Demo steps
- Select a different instrument
- Data for the selected instrument is displayed

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by alvyn279** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Run and open web app | N/A    | N/A | N/A   |
| Click orderbook on side bar | N/A | Orderbook shows on dashboard | PASS   |
| Select instrument from drop down in top left | N/A | Nothing visual should happen | PASS  |
| Select date, timestamp | Date, timestamp | Observe orderbook being displayed correctly | PASS  |
