### ISSUE TITLE
Graph of top-of-book over time

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#86]
As a user, I want to see an L1 view of the orderbook as a graph, representing the best bid and best ask over time.

Tasks: #108, #111, #157

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 13 |
| Priority     | High |
| Risk         | High |

# Tasks
- Preprocess data set for L1 view
- Add graph component to the front-end
- Service route to serve data points based on bounds and granularity

# Demo steps
- Graph of the top-of-book is displayed on the page
- Graph is zoomable from a day to less than microseconds

## Customer signoff
- [ ] Pierre-Marc Fournier

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by chimano** [comment]
### Acceptance test
| Steps                    | Inputs | Expected Outputs                                          | Status |
|--------------------------|--------|----------------------------------------------------------|--------|
| Visit the home page and visit the orderbook page | N/A | N/A | N/A   |
| Select an instrument, and select January 1, 2020 as a day |  N/A    | The orderbook should be displayed along with a graph depicting the best bid and best ask through the selected date | Not yet tested |
| Click on a point in the graph| N/A  | The contents of the orderbook should be shown for that point in time, The list of messages should show the most recent message applied at the selected point in time| Not yet tested|
